version: '3.4'

services:
  apigateway:
    image: ${DOCKER_REGISTRY-}apigateway
    build:
      context: .
      dockerfile: MGR.ApiGateway/Dockerfile


  demoapi1:
    image: ${DOCKER_REGISTRY-}coffeeapi
    build:
      context: .
      dockerfile: CoffeeApi/Dockerfile


  demoapi2:
    image: ${DOCKER_REGISTRY-}teaapi
    build:
      context: .
      dockerfile: TeaApi/Dockerfile

