version: '3.4'

services:
  apigateway:
    image: ${DOCKER_REGISTRY-}apigateway
    build:
      context: .
      dockerfile: ApiGateway/Dockerfile


  coffeeapi:
    image: ${DOCKER_REGISTRY-}coffeeapi
    build:
      context: .
      dockerfile: CoffeeApi/Dockerfile


  teaapi:
    image: ${DOCKER_REGISTRY-}teaapi
    build:
      context: .
      dockerfile: TeaApi/Dockerfile

